version: '3.8'

services:
  fastapi-app:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - fastapi_summarizer

networks:
  fastapi_summarizer:
    driver: bridge